### ISSUE TITLE
Problem with stacktrace

### ISSUE THREAD

**Issue by sajt** [othiym23/bug-clinic#20]
I downloaded the solution.js from problems/stacktraces. But when I try the 
```
bug-clinic run solution.js
```
I get the following error:
```
TAP version 13
# (anonymous)
ok 1 loaded scenario OK
not ok 2 TypeError: path must be a string
  ---
    operator: error
    expected: undefined
    actual:   [TypeError: path must be a string]
    stack:
      TypeError: path must be a string
        at TypeError (native)
        at Object.fs.open (fs.js:491:11)
        at Object.open (/Users/sajt/Sites/ember/js/node_modules/stackup/node_modules/async-listener/index.js:18:15)
        at fs.readFile (fs.js:262:6)
        at /Users/sajt/Sites/ember/js/node_modules/stackup/node_modules/async-listener/index.js:18:15
        at Domain.<anonymous> (/Users/sajt/Sites/ember/js/solution.js:14:5)
        at Domain.run (domain.js:197:16)
        at scenario (/Users/sajt/Sites/ember/js/solution.js:13:5)
        at verify (/usr/local/lib/node_modules/bug-clinic/problems/bunyan/index.js:28:9)
        at Test.<anonymous> (/usr/local/lib/node_modules/bug-clinic/node_modules/adventure-verify/index.js:48:40)
        at Test.bound [as _cb] (/usr/local/lib/node_modules/bug-clinic/node_modules/adventure-verify/node_modules/tape/lib/test.js:60:32)
        at Test.run (/usr/local/lib/node_modules/bug-clinic/node_modules/adventure-verify/node_modules/tape/lib/test.js:74:14)
        at Test.bound [as run] (/usr/local/lib/node_modules/bug-clinic/node_modules/adventure-verify/node_modules/tape/lib/test.js:60:32)
        at Immediate.next [as _onImmediate] (/usr/local/lib/node_modules/bug-clinic/node_modules/adventure-verify/node_modules/tape/lib/results.js:66:15)
        at processImmediate [as _immediateCallback] (timers.js:367:17)
  ...

1..2
# tests 2
# pass  1
# fail  1
```

Why is it?

**Comment by sajt** [comment]
When I deleted all other files from the directory the test passed.
