### ISSUE TITLE
Test challenge fails

### ISSUE THREAD

**Issue by alexvicegrab** [othiym23/bug-clinic#26]
Regardless of whether I fix the isGreaterThanZero function, I see this weird error.

```
TAP version 13
# (anonymous)
not ok 1 TypeError: t.ok is not a function
  ---
    operator: error
    expected: undefined
    actual:   [TypeError: t.ok is not a function]
    stack:
      TypeError: t.ok is not a function
        at scenario (/Users/sasha/Projects/nodeschool/bug-clinic/tape.js:4:5)
        at Domain.<anonymous> (/usr/local/lib/node_modules/bug-clinic/problems/stacktraces/index.js:31:9)
        at Domain.run (domain.js:221:14)
        at verify (/usr/local/lib/node_modules/bug-clinic/problems/stacktraces/index.js:30:11)
        at Test.<anonymous> (/usr/local/lib/node_modules/bug-clinic/node_modules/adventure-verify/index.js:48:40)
        at Test.bound [as _cb] (/usr/local/lib/node_modules/bug-clinic/node_modules/tape/lib/test.js:60:32)
        at Test.run (/usr/local/lib/node_modules/bug-clinic/node_modules/tape/lib/test.js:74:14)
        at Test.bound [as run] (/usr/local/lib/node_modules/bug-clinic/node_modules/tape/lib/test.js:60:32)
        at Immediate.next (/usr/local/lib/node_modules/bug-clinic/node_modules/tape/lib/results.js:66:15)
        at runCallback (timers.js:672:20)
  ...

1..1
# tests 1
# pass  0
# fail  1
```

**Comment by pleasezoomout** [comment]
Im having the same error.

**Comment by yair5124** [comment]
Having the same issue
According to stack trace it seems that bug-clinic is verifying the tape exercise using the stacktrace program. 
Could this occur when the stacktrace exercise have not been completed ?

**Comment by alexvicegrab** [comment]
Unaddressed for over 1 year, closing this.
